# Generated by Django 6.0.1 on 2026-08-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Spouse', 'Spouse'), ('Friend', 'Friend'), ('Caregiver', 'Caregiver'), ('Other', 'Other')], max_length=50),
        ),
    ]
