# Generated by Django 6.1 on 2026-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_alter_emergencycontact_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Friend', 'Friend'), ('Caregiver', 'Caregiver'), ('Other', 'Other')], max_length=50),
        ),
    ]
